"""
GitHub integration service (Sprint 7).

Creates pull requests via the GitHub REST API after successful
implementation + validation runs.
"""
from __future__ import annotations
import httpx


async def create_pr(
    repo: str,
    head_branch: str,
    base_branch: str,
    title: str,
    body: str,
    token: str,
) -> str:
    """
    Create a GitHub pull request. Returns the PR HTML URL.
    Raises httpx.HTTPStatusError on API failure.
    """
    async with httpx.AsyncClient(timeout=15.0) as client:
        r = await client.post(
            f"https://api.github.com/repos/{repo}/pulls",
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            json={
                "title": title,
                "body": body,
                "head": head_branch,
                "base": base_branch,
            },
        )
        # 422 = PR already exists for this branch
        if r.status_code == 422:
            data = r.json()
            errors = data.get("errors", [])
            for e in errors:
                if "pull request already exists" in str(e.get("message", "")).lower():
                    # Find the existing PR URL
                    existing = await _find_existing_pr(repo, head_branch, base_branch, token, client)
                    if existing:
                        return existing
            r.raise_for_status()
        else:
            r.raise_for_status()
        return r.json()["html_url"]


async def _find_existing_pr(
    repo: str,
    head: str,
    base: str,
    token: str,
    client: httpx.AsyncClient,
) -> str | None:
    """Return HTML URL of an existing open PR for the given head branch."""
    r = await client.get(
        f"https://api.github.com/repos/{repo}/pulls",
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
        },
        params={"head": head, "base": base, "state": "open"},
    )
    if r.is_success and r.json():
        return r.json()[0]["html_url"]
    return None


def build_pr_body(
    task_title: str,
    task_description: str,
    diff_stat: str,
    test_results: dict | None,
    token_input: int,
    token_output: int,
    cost_usd: float,
) -> str:
    """Compose a structured PR body from execution metadata."""
    lines: list[str] = [
        f"## {task_title}",
        "",
    ]

    if task_description:
        lines += [task_description, ""]

    if diff_stat:
        lines += ["## Changes", "```", diff_stat, "```", ""]

    if test_results:
        p = test_results.get("passed", 0)
        f = test_results.get("failed", 0)
        e = test_results.get("errors", 0)
        status = "All tests passing" if f == 0 and e == 0 else f"{f} failed, {e} errors"
        lines += [
            "## Tests",
            f"- {status}: {p} passed, {f} failed, {e} errors",
            "",
        ]

    lines += [
        "## Execution",
        f"- Tokens: {token_input:,} in / {token_output:,} out",
        f"- Cost: ${cost_usd:.4f}",
        "",
        "---",
        "*Generated by [Kanban AI Orchestrator](https://github.com/anthropics/claude-code)*",
    ]

    return "\n".join(lines)
